/**
 * Javascript implementation of RSA-KEM.
 *
 * @author Lautaro Cozzani Rodriguez
 * @author Dave Longley
 *
 * Copyright (c) 2014 Lautaro Cozzani <lautaro.cozzani@scytl.com>
 * Copyright (c) 2014 Digital Bazaar, Inc.
 */
!function(){function e(e){function t(t,n,r,i){t.generate=function(t,u){for(var f=new e.util.ByteBuffer,o=Math.ceil(u/i)+r,a=new e.util.ByteBuffer,l=r;o>l;++l){a.putInt32(l),n.start(),n.update(t+a.getBytes());var c=n.digest();f.putBytes(c.getBytes(i))}return f.truncate(f.length()-u),f.getBytes()}}e.kem=e.kem||{};var n=e.jsbn.BigInteger;e.kem.rsa={},e.kem.rsa.create=function(t,r){r=r||{};var i=r.prng||e.random,u={};return u.encrypt=function(r,u){var f,o=Math.ceil(r.n.bitLength()/8);do f=new n(e.util.bytesToHex(i.getBytesSync(o)),16).mod(r.n);while(f.equals(n.ZERO));f=e.util.hexToBytes(f.toString(16));var a=o-f.length;a>0&&(f=e.util.fillString(String.fromCharCode(0),a)+f);var l=r.encrypt(f,"NONE"),c=t.generate(f,u);return{encapsulation:l,key:c}},u.decrypt=function(e,n,r){var i=e.decrypt(n,"NONE");return t.generate(i,r)},u},e.kem.kdf1=function(e,n){t(this,e,0,n||e.digestLength)},e.kem.kdf2=function(e,n){t(this,e,1,n||e.digestLength)}}var t="kem";if("function"!=typeof define){if("object"!=typeof module||!module.exports)return"undefined"==typeof forge&&(forge={}),e(forge);var n=!0;define=function(e,t){t(require,module)}}var r,i=function(n,i){i.exports=function(i){var u=r.map(function(e){return n(e)}).concat(e);if(i=i||{},i.defined=i.defined||{},i.defined[t])return i[t];i.defined[t]=!0;for(var f=0;f<u.length;++f)u[f](i);return i[t]}},u=define;define=function(e,t){return r="string"==typeof e?t.slice(2):e.slice(2),n?(delete define,u.apply(null,Array.prototype.slice.call(arguments,0))):(define=u,define.apply(null,Array.prototype.slice.call(arguments,0)))},define(["require","module","./util","./random","./jsbn"],function(){i.apply(null,Array.prototype.slice.call(arguments,0))})}();