/**
 * Password-Based Key-Derivation Function #2 implementation.
 *
 * See RFC 2898 for details.
 *
 * @author Dave Longley
 *
 * Copyright (c) 2010-2013 Digital Bazaar, Inc.
 */
!function(){function e(e){var t,n=e.pkcs5=e.pkcs5||{},r="undefined"!=typeof process&&process.versions&&process.versions.node;r&&!e.disableNativeCode&&(t=require("crypto")),e.pbkdf1=n.pbkdf1=function(t,n,r,i,o){("undefined"==typeof o||null===o)&&(o=e.md.sha1.create());var u=o.digestLength;if(i>u)throw new Error("Derived key is too long.");o.update(t),o.update(n);for(var d=o.digest().getBytes(),f=1;r>f;++f)o.start(),d=o.update(d).digest().getBytes();return d=d.slice(0,i)},e.pbkdf2=n.pbkdf2=function(n,i,o,u,d,f){function l(){return k>c?f(null,m):(g.start(null,null),g.update(i),g.update(e.util.int32ToBytes(k)),v=h=g.digest().getBytes(),B=2,void a())}function a(){return o>=B?(g.start(null,null),g.update(h),b=g.digest().getBytes(),v=e.util.xorBytes(v,b,s),h=b,++B,e.util.setImmediate(a)):(m+=c>k?v:v.substr(0,y),++k,void l())}if("function"==typeof d&&(f=d,d=null),r&&!e.disableNativeCode&&t.pbkdf2&&(null===d||"object"!=typeof d)&&(t.pbkdf2Sync.length>4||!d||"sha1"===d))return"string"!=typeof d&&(d="sha1"),i=new Buffer(i,"binary"),f?4===t.pbkdf2Sync.length?t.pbkdf2(n,i,o,u,function(e,t){return e?f(e):void f(null,t.toString("binary"))}):t.pbkdf2(n,i,o,u,d,function(e,t){return e?f(e):void f(null,t.toString("binary"))}):4===t.pbkdf2Sync.length?t.pbkdf2Sync(n,i,o,u).toString("binary"):t.pbkdf2Sync(n,i,o,u,d).toString("binary");if(("undefined"==typeof d||null===d)&&(d=e.md.sha1.create()),"string"==typeof d){if(!(d in e.md.algorithms))throw new Error("Unknown hash algorithm: "+d);d=e.md[d].create()}var s=d.digestLength;if(u>4294967295*s){var p=new Error("Derived key is too long.");if(f)return f(p);throw p}var c=Math.ceil(u/s),y=u-(c-1)*s,g=e.hmac.create();g.start(d,n);var v,b,h,m="";if(!f){for(var k=1;c>=k;++k){g.start(null,null),g.update(i),g.update(e.util.int32ToBytes(k)),v=h=g.digest().getBytes();for(var B=2;o>=B;++B)g.start(null,null),g.update(h),b=g.digest().getBytes(),v=e.util.xorBytes(v,b,s),h=b;m+=c>k?v:v.substr(0,y)}return m}var B,k=1;l()}}var t="pbkdf2";if("function"!=typeof define){if("object"!=typeof module||!module.exports)return"undefined"==typeof forge&&(forge={}),e(forge);var n=!0;define=function(e,t){t(require,module)}}var r,i=function(n,i){i.exports=function(i){var o=r.map(function(e){return n(e)}).concat(e);if(i=i||{},i.defined=i.defined||{},i.defined[t])return i[t];i.defined[t]=!0;for(var u=0;u<o.length;++u)o[u](i);return i[t]}},o=define;define=function(e,t){return r="string"==typeof e?t.slice(2):e.slice(2),n?(delete define,o.apply(null,Array.prototype.slice.call(arguments,0))):(define=o,define.apply(null,Array.prototype.slice.call(arguments,0)))},define(["require","module","./hmac","./md","./util"],function(){i.apply(null,Array.prototype.slice.call(arguments,0))})}();