CREATE TABLE `isign_ca_cert` (
`ID` VARCHAR(512) NOT NULL COMMENT '인증서 고유정보(SERIAL NUMBER_DN)',
`DN` VARCHAR(256) NOT NULL COMMENT '인증서 고유 이름',
`SERIALNUMBER` CHAR(128) NOT NULL COMMENT '인증서 고유번호',
`ISSUERDN` CHAR(255) NOT NULL COMMENT '인증서 발급자 고유 이름',
`SKID` VARCHAR(256) NULL COMMENT 'Subject Key ID',
`AKID` VARCHAR(256) NULL COMMENT 'Authority Key ID',
`NOTAFTER` VARCHAR(32) NOT NULL COMMENT '인증서 만료일',
`NOTBEFORE` VARCHAR(32) NOT NULL COMMENT '인증서 종료일',
`CERTIFICATE` VARCHAR(4096) NOT NULL COMMENT '인증서(BASE64 인코딩)',
`PID` VARCHAR(512) NOT NULL COMMENT '해당 인증서에 서명한 CA(Root CA)의 ID'
)
COMMENT='CA, Root CA 인증서 정보 저장'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
ALTER TABLE `isign_ca_cert`
ADD PRIMARY KEY (`SERIALNUMBER`, `ISSUERDN`);

INSERT INTO `isign_config` (`config_key`, `config_value`) VALUES ('VERIFY_CERT_CRL_USE_B', 'false');
