ALTER TABLE `isign_service` ADD COLUMN `ACCESS_CONTROL_POLICY` VARCHAR(10) NOT NULL COMMENT '접근 제어 정책(1 : white list, 0 : black list)' AFTER `USE_IP_CONTROL`;
UPDATE isign_service SET ACCESS_CONTROL_POLICY = "1" where CHECKALLOWIP = "1";
UPDATE isign_service SET ACCESS_CONTROL_POLICY = "0" where CHECKALLOWIP = "0";
ALTER TABLE `isign_service` DROP COLUMN `CHECKALLOWIP`;
ALTER TABLE `isign_service` DROP COLUMN `CHECKDENYIP`;