INSERT INTO `isign_api_user` (`api_key`, `api_secretkey`, `api_email`) VALUES
	('openapi', 'nqSdAU2mPMbxSXFKsxyeZQ==', 'openapi@pentasecurity.com');

INSERT INTO `isign_role` (`NAME`, `DESCR`, `CRTADMINSID`, `CRTDATE`, `MDFADMINSID`, `MDFDATE`, `RTYPE`) VALUES
	('OPENAPI', 'OPENAPI TEST', 1, NULL, NULL, NULL, NULL);	
	
INSERT INTO `isign_roleservicemap` (`SSID`, `CRTADMINSID`, `CRTDATE`, `MDFADMINSID`, `MDFDATE`, `USERDATA`, `RESERVED1`, `RESERVED2`) VALUES
	(1, 1, '2017-01-24 05:34:13', NULL, NULL, NULL, NULL, NULL);
	
INSERT INTO `isign_role_accesslistmap` (`RID`, `SSID`, `CODE_NAME`, `CODE_USE`) VALUES
	(1, 1, 'http://openapi.test.com', '1');
	
INSERT INTO `isign_dept` (`SID`, `NAME_KOR`, `NAME_ENG`, `PARENTSID`, `TYPECODE`, `TYPENAME`, `LOCALHQCODE`, `DEPTH`) VALUES
	(0, '전체', NULL, '0', NULL, NULL, NULL, 0),
	(1, 'penta', NULL, '0', NULL, NULL, NULL, 1),
	(2, '기획실', NULL, '0', NULL, NULL, NULL, 1),
	(3, '운영1', NULL, '0', NULL, NULL, NULL, 1),
	(4, '개발1', NULL, '0', NULL, NULL, NULL, 1),
	(5, '개발2', NULL, '0', NULL, NULL, NULL, 1),
	(6, '비서실', NULL, '0', NULL, NULL, NULL, 1);

INSERT INTO `isign_title` (`SID`, `NAME_KOR`, `NAME_ENG`) VALUES
	('001', '대표이사', ''),
	('002', '이사', ''),
	('003', '상무', ''),
	('004', '팀장', ''),
	('005', '차장', ''),
	('006', '과장', ''),
	('007', '대리', ''),
	('008', '주임', ''),
	('009', '사원', ''),
	('010', '부장', '');	

INSERT INTO `isign_user` (`ID`, `PWD`, `NAME_KOR`, `NAME_ENG`, `NAME_CHN`, `RESID`, `EMPID`, `EMAIL`, `OFFICEPHONE`, `MOBILE`, `DEPARTCODE`, `TITLECODE`, `POSITIONCODE`, `PRIMARYDUTYCODE`, `SUBDUTYCODE`, `EMPGROUPCODE`, `ADDITIONALTITLECODE`, `ISADMIN`, `ADMINSID`, `EMPTYPE`, `CRTADMINSID`, `CRTDATE`, `MDFADMINSID`, `MDFDATE`, `MDFREASON`, `PROVINCE`, `COUNTY`, `STREET`, `POB`, `ZIPCODE`, `ADDR`, `HOMEADDR`, `HOMEPHONE`, `FAX`, `PKIDN`, `PKISN`, `EMPLOYMENT_STATUS`, `SAML_NAM_ID`, `NOTES_ID`, `MOTP_KEY`, `USE_IP_CONTROL`) VALUES
	('penta', 'A6xnQhbz4Vx2HuGl4lXwZ5U2I8iziLRFnhP5eNfIRvQ=', '펜타', NULL, NULL, '', '12345', '', NULL, NULL, 1, 1, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, 'penta01', NULL, '0');
	
INSERT INTO `isign_motp_history` (`INCORRECTTIME`, `INCORRECTNUM`, `LASTVERIFIED`, `ISDEFAULTOTP`) VALUES
	(NULL, NULL, NULL, 1);
	
INSERT INTO `isign_pwdhistory` (`SID`, `LASTCHANGEDATE`, `INCORRECTTIME`, `ISDEFAULTPWD`, `INCORECTNUM`) VALUES
	(1, '2017-01-24 05:34:13', '2017-01-31 04:52:17', 0, 0);

INSERT INTO `isign_servicegroup` (`SID`, `NAME`, `DESCR`) VALUES
	(1, 'testgroup', '');	
	
INSERT INTO `isign_service` (`NAME`, `DESCR`, `STYPE`, `SVCGROUPSID`, `RETURNURL`, `OUTURL`, `IP`, `PORT`, `SERVERTYPE`, `SERVERTYPE2`, `ACSTIMEFROM`, `ACSTIMETO`, `ISENCRYPT`, `AUTHMETHOD`, `ISMUTUAL`, `REQUESTAGENT`, `CHECKALLOWIP`, `CHECKDENYIP`, `CRTADMINSID`, `CRTDATE`, `MDFADMINSID`, `MDFDATE`, `DN`, `NOTIFY`, `USEISIGNPAGE`, `USEISIGNPAGE2`, `PATHURL`, `AUTHURL`, `AUTHURL2`, `AUTHORIZATION_URL`, `LOGOUTURL`, `USE_IP_CONTROL`, `AUTHMETHOD2`, `DEFAULT_SERVICE`) VALUES
	('JSP', NULL, '002', 1, 'http://isign1.pentasecurity.com', NULL, NULL, '8080', 'JSP', NULL, NULL, NULL, NULL, 'idpw', NULL, NULL, '1', '0', 1, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, 'http://10.0.81.160:8080/sso/checkauth.jsp', NULL, '0', 'disabled', '1'),
	('ASP', NULL, '002', 1, 'http://isign2.pentasecurity.com', NULL, NULL, '80', 'ASP', NULL, NULL, NULL, NULL, 'idpw', NULL, NULL, '1', '0', 1, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, 'http://10.0.81.161:8080/sso/checkauth.jsp', NULL, '0', 'disabled', '0'),
	('IDP', NULL, '002', 1, 'http://localhost', NULL, NULL, '8080', 'IDP', NULL, NULL, NULL, NULL, 'idpw', NULL, NULL, '1', '0', 1, NULL, NULL, NULL, NULL, NULL, 1, NULL, '/authentication/saml2/idp/response', NULL, NULL, NULL, NULL, '0', NULL, '0'),
	('SP', NULL, '002', 1, 'http://localhost', NULL, NULL, '8080', 'SP', NULL, NULL, NULL, NULL, 'idpw', NULL, NULL, '1', '0', 1, NULL, NULL, NULL, NULL, NULL, 1, NULL, '/authentication/saml2/sp', NULL, NULL, NULL, NULL, '0', NULL, '0');

insert into isign_config (config_key, config_value) VALUES ('HMAC_KEY_T', 'yI&6LF_Gq?fv%PWCzjY?nEtPZh+SCeSgv.KjMM%vIBE_V2PBtid&kkYX%Lb@A2th');
	
INSERT INTO `isign_idp_info` (`ENTITY_ID`, `DOMAIN_NAME`, `LOGIN_SERVICE`, `LOGOUT_SERVICE`, `ASSERTION_CONSUMER_SERVICE`, `PROVIDER_NAME`, `RELAYSTATE_URL`, `PUBLIC_KEY_VALUE`) VALUES
	('qa1.pentasecurity.com', 'https://qa1.pentasecurity.com', 'https://idp.pentasecurity.com/simplesaml/saml2/idp/SSOService.php?spentityid=qa1.pentasecurity.com', 'https://qa1.pentasecurity.com/isignplus/logout.jsp', 'https://qa1.pentasecurity.com/acs', 'simplesaml', 'http://192.168.21.87:8080/sso/business.jsp', 'MIIDmTCCAoGgAwIBAgIJAOgGbov1jR4gMA0GCSqGSIb3DQEBBQUAMGMxCzAJBgNVBAYTAktSMQwwCgYDVQQIDANJZFAxDjAMBgNVBAcMBVNlb3VsMQ8wDQYDVQQKDAZHR0VMT1MxDDAKBgNVBAsMA0RFVjEXMBUGA1UEAwwOaWRwLmdnZWxvcy5jb20wHhcNMTMwNjAyMTI0OTUwWhcNMjMwNjAyMTI0OTUwWjBjMQswCQYDVQQGEwJLUjEMMAoGA1UECAwDSWRQMQ4wDAYDVQQHDAVTZW91bDEPMA0GA1UECgwGR0dFTE9TMQwwCgYDVQQLDANERVYxFzAVBgNVBAMMDmlkcC5nZ2Vsb3MuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwNvQNBWb+v2Lnzk2ZGOxDW9Us/jl8Z4rtjN1RXpJ2UzoTPJ2szheZfoFnBsCGPkfIpmLrPB0PaizqGvSrC7pp1M0Fc5kAUr5slbUA5kHHG6/Bxoc1ulaLb3oNnADwRd+uF9vTDZyd002HMMljgPsyxU/RC5x8Qcw3TQAVu7ST9yVbfVPMK0LSM5CCUILGx4aEz2SQwlXKqYJ3F5hlGQdOmQdUQK/gb5HHdmNjiNprBx35txN8SLJxP3ZDcBJRsRf/ZQDMUM8mtr0HoGRIn64PqIm9+3LUomrW7+4GUgWDygXIWbUC6ay/3mZkMiLwQDNwXqO6iS3xowi8CDEJlMftwIDAQABo1AwTjAdBgNVHQ4EFgQUOAJ1RTZW2GYs8O7b236cK8DXqFEwHwYDVR0jBBgwFoAUOAJ1RTZW2GYs8O7b236cK8DXqFEwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQUFAAOCAQEAfOkPuLMZMrKt2VdnqZJASoOCRMmlo77o8e3kDcImSPNCR8LVac+2+vziLf9xPvbNzaUh7PmQ+5xn50XXjy6gkzOzoSlrPZw9r74YwsF7KtKxwhxW/7Z1EPfVjEeeAFqH2UrVV/Fbo8lkYB6o8f5GPXr5sm76qoPqoHjG8z2Hj2huQdDVWXStVIULFDemjzHqk2sA6h46a2ZU1CDFjCOj+bcY0k4ciGM0ulFn+pT3t7EHQmdIPRpnfh/KkvUpo0WYCT3JclDmhAqgAvHs22Y6lyNfKa1RscIe+7oliF9ayTH3OCd2dHCISNKH6SxWhjaQ1DO6gIRt8xCuDnfzp0lMg==');	
	
INSERT INTO `isign_sp_info` (`ENTITY_ID`, `PROVIDER_NAME`, `ASSERTION_CONSUMER_SERVICE`, `LOGOUT_SERVICE`, `DESCRIPTION`, `PRIVATE_KEY_VALUE`, `PUBLIC_KEY_VALUE`, `DOMAIN_NAME`) VALUES
	('qa1.pentasecurity.com', 'isign+', 'https://qa1.pentasecurity.com/acs', 'https://qa1.pentasecurity.com/isignplus/logout.jsp', NULL, 'MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDA29A0FZv6/YufOTZkY7ENb1Sz+OXxniu2M3VFeknZTOhM8nazOF5l+gWcGwIY+R8imYus8HQ9qLOoa9KsLumnUzQVzmQBSvmyVtQDmQccbr8HGhzW6Votveg2cAPBF364X29MNnJ3TTYcwyWOA+zLFT9ELnHxBzDdNABW7tJP3JVt9U8wrQtIzkIJQgsbHhoTPZJDCVcqpgncXmGUZB06ZB1RAr+Bvkcd2Y2OI2msHHfm3E3xIsnE/dkNwElGxF/9lAMxQzya2vQegZEifrg+oib37ctSiatbv7gZSBYPKBchZtQLprL/eZmQyIvBAM3Beo7qJLfGjCLwIMQmUx+3AgMBAAECggEAZiAAUJRg1LgOh3I0a1SfHQ4nPGZA3YF0hDcbkn7/PCKNoLGEScM/uaB79/4VTkQdSKUmYZ2y8DO1byoplSQCdqiInEN+kXCyaM2x13XhXh0G6yvYubU4G6DEpo8KbeWTJO7kcOckFii8zt5HtLw/WAsYRXKSw5+bMIeo5l/w3nh0DNM3SvyHdNk2N3CtHfu4M/mv9103bR/lOpKignXhWltLd869gyC0p7pOHg6FOq0gvWVeqREmmH3AWU/CnK7uu68E2/VB3mpJTUSps5kk1FT/97TVyX4cUrpK2EIGaQStrF/YDvrkHhLwZ+beefEwD8jAnZAGb9zoxprf+CqAgQKBgQD0A41BtRIVWK6t2zSYKNXgth7VrptxP95rqt1Rb5jz751EEGsMv2ccd/p2/h+j/65PkGTpbE8z3HssV6rkoy5PeU9srAcygIUoYAal+1jnttqxR5X/F8YSmxoG3+K9KyMpoAPZ5OblW3JBu632V0i6cpSLsYlbOveZw5tm2P5z9QKBgQDKVP1xs2ddb/D+opyzKbCDmtWH7p9cOL3N6r+FToNfdvGIBuuTd+D249fYazcW7RdxFScLp//3U8PCnLT+zuP++Gw9rvD9kKBU9BRNSkx3FbFbZKcDH9NAWCUPoHTRjPOlgFe7XqwR6X6PsnflT6M6mptMeBm9F4kGBTDtRbMlewKBgEJ6wT5YlZ+pNJX7Nb4KyhJZq9btpj3Zd8B/oaJxNAupiYAktPWZI/92lI9ctsQYgaX9ofCSaJWpiQlQrSdzacePNltWFvPkXeLdHpKUAunGQJix9ySzlmw1Q4cB8iU1nnPVu5berSVpn5xXBJMrvo3Fb8ELUm+/hfundiw0DEcNAoGBAMgyEdeHqJXGJhD9Osj3TgTZlb/69kkch4kQZdHz3n79xHxQRJVUPw5qYG5tn0Oa8d/dCxY4c0b35bFQtrGMagElMoxR5Xcuu8VzAAd9pW0K1MLWM34e5jo7POhaXlvc+FLgS25EfUL34lcyQflts9dPlKu0BduYRubjCgcrONezAoGBAOHul7XKE+laKaVEwcZYCjN2AhiH24r1B6SSpHYW9VQ3RZYL+Ou9yGadcm7A+G8xzXTEjzQgBsDnXb+IQmuR1FtOGMJHRq2R36jZs7LR4tY/8AMwG3hmN1F+lQYAEbmChIsOWXXlQn/Y04M6BFiagfOArUIbwCgZhUZ+KPlt3oWG', 'MIIDmTCCAoGgAwIBAgIJAOgGbov1jR4gMA0GCSqGSIb3DQEBBQUAMGMxCzAJBgNVBAYTAktSMQwwCgYDVQQIDANJZFAxDjAMBgNVBAcMBVNlb3VsMQ8wDQYDVQQKDAZHR0VMT1MxDDAKBgNVBAsMA0RFVjEXMBUGA1UEAwwOaWRwLmdnZWxvcy5jb20wHhcNMTMwNjAyMTI0OTUwWhcNMjMwNjAyMTI0OTUwWjBjMQswCQYDVQQGEwJLUjEMMAoGA1UECAwDSWRQMQ4wDAYDVQQHDAVTZW91bDEPMA0GA1UECgwGR0dFTE9TMQwwCgYDVQQLDANERVYxFzAVBgNVBAMMDmlkcC5nZ2Vsb3MuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwNvQNBWb+v2Lnzk2ZGOxDW9Us/jl8Z4rtjN1RXpJ2UzoTPJ2szheZfoFnBsCGPkfIpmLrPB0PaizqGvSrC7pp1M0Fc5kAUr5slbUA5kHHG6/Bxoc1ulaLb3oNnADwRd+uF9vTDZyd002HMMljgPsyxU/RC5x8Qcw3TQAVu7ST9yVbfVPMK0LSM5CCUILGx4aEz2SQwlXKqYJ3F5hlGQdOmQdUQK/gb5HHdmNjiNprBx35txN8SLJxP3ZDcBJRsRf/ZQDMUM8mtr0HoGRIn64PqIm9+3LUomrW7+4GUgWDygXIWbUC6ay/3mZkMiLwQDNwXqO6iS3xowi8CDEJlMftwIDAQABo1AwTjAdBgNVHQ4EFgQUOAJ1RTZW2GYs8O7b236cK8DXqFEwHwYDVR0jBBgwFoAUOAJ1RTZW2GYs8O7b236cK8DXqFEwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQUFAAOCAQEAfOkPuLMZMrKt2VdnqZJASoOCRMmlo77o8e3kDcImSPNCR8LVac+2+vziLf9xPvbNzaUh7PmQ+5xn50XXjy6gkzOzoSlrPZw9r74YwsF7KtKxwhxW/7Z1EPfVjEeeAFqH2UrVV/Fbo8lkYB6o8f5GPXr5sm76qoPqoHjG8z2Hj2huQdDVWXStVIULFDemjzHqk2sA6h46a2ZU1CDFjCOj+bcY0k4ciGM0ulFn+pT3t7EHQmdIPRpnfh/KkvUpo0WYCT3JQclDmhAqgAvHs22Y6lyNfKa1RscIe+7oliF9ayTH3OCd2dHCISNKH6SxWhjaQ1DO6gIRt8xCuDnfzp0lMg==', 'qa1.pentasecurity.com');	