ALTER TABLE `isign_config` CHANGE COLUMN `config_value` `config_value` VARCHAR(4096) NULL DEFAULT NULL COMMENT '설정정보 값' AFTER `config_key`;
INSERT INTO `isign_config` (`config_key`, `config_value`) values ('LICENSE_FILE_T', '');
INSERT INTO `isign_config` (`config_key`, `config_value`) values ('LICENSE_FIDO_UAF_B', 'false');
INSERT INTO `isign_config` (`config_key`, `config_value`) values ('LICENSE_FIDO_U2F_B', 'false');
INSERT INTO `isign_config` (`config_key`, `config_value`) values ('LICENSE_IDPW_B', 'false');
INSERT INTO `isign_config` (`config_key`, `config_value`) values ('LICENSE_KERBEROS_B', 'false');
INSERT INTO `isign_config` (`config_key`, `config_value`) values ('LICENSE_OTP_B', 'false');
INSERT INTO `isign_config` (`config_key`, `config_value`) values ('LICENSE_PKI_B', 'false');
INSERT INTO `isign_config` (`config_key`, `config_value`) values ('LICENSE_SAML_B', 'false');
INSERT INTO `isign_config` (`config_key`, `config_value`) values ('LICENSE_CS_AGENT_B', 'false');
INSERT INTO `isign_config` (`config_key`, `config_value`) values ('LICENSE_NOTES_AGENT_B', 'false');
INSERT INTO `isign_config` (`config_key`, `config_value`) values ('LICENSE_SAP_AGENT_B', 'false');
