DELETE FROM ISIGN_SERVICE where SID = '100000';
DELETE FROM ISIGN_SERVICE where SID = '200000';
INSERT INTO `isign_servicegroup` (`SID`, `NAME`, `DESCR`) VALUES
	(100000, 'SAML Service Group', '');	
INSERT INTO ISIGN_SERVICE(SID, NAME, SVCGROUPSID, AUTHMETHOD, AUTHMETHOD2, CRTADMINSID, CRTDATE, USEISIGNPAGE, USE_IP_CONTROL, DEFAULT_SERVICE, RETURNURL) 
VALUES('100000', 'SAML IdP', '100000', 'idpw', 'disabled','1', now(), '1', '0', '0', 'SAML IdP');