CREATE TABLE ANI(
ANI_ID	NUMBER(10,0),
TITLE	VARCHAR2(100 CHAR),
ANI_TIME	VARCHAR2(100 CHAR),
DAY	VARCHAR2(100 CHAR),
KEYWORD	VARCHAR2(100 CHAR),
SITE	VARCHAR2(30 CHAR)
);

CREATE TABLE BOARD(
B_ID NUMBER PRIMARY KEY,
B_GROUP NUMBER,
B_LEVEL NUMBER,
TITLE VARCHAR2(255),
USER_NICK VARCHAR2(255),
CONTENT CLOB,
VIEW_COUNT NUMBER,
NOTICE CHAR,
SECRET CHAR,
PASSWORD VARCHAR2(255),
REGISTER_DATE DATE,
MODIFY_DATE DATE,
DELETE_STATUS CHAR,
TMP_FIELD1 VARCHAR2(255),
TMP_FIELD2 VARCHAR2(255),
TMP_FIELD3 VARCHAR2(255),
TMP_FIELD4 VARCHAR2(255),
TMP_FIELD5 VARCHAR2(255),
TMP_FIELD6 VARCHAR2(255),
TMP_FIELD7 VARCHAR2(255),
TMP_FIELD8 VARCHAR2(255),
TMP_FIELD9 VARCHAR2(255),
TMP_FIELD10 VARCHAR2(255)
);

CREATE TABLE BOARD_COMMENT(
C_ID NUMBER PRIMARY KEY,
B_ID NUMBER,
USER_NICK VARCHAR2(255),
CONTENT CLOB,
C_GROUP NUMBER,
C_LEVEL NUMBER,
REGISTER_DATE DATE,
DELETE_STATUS CHAR
);

CREATE TABLE BOARD_FILE(
F_ID NUMBER PRIMARY KEY,
B_ID NUMBER,
DIRECTORY VARCHAR2(255),
SAVE_NAME VARCHAR2(255),
REAL_NAME VARCHAR2(255)
);
CREATE SEQUENCE F_ID_SEQ
START WITH 1
INCREMENT BY 1;

CREATE TABLE INSTA(
NAME	VARCHAR2(100 CHAR),
ADDR	VARCHAR2(100 CHAR)
);

CREATE TABLE LOGIN(
ID	VARCHAR2(100 CHAR),
PW	VARCHAR2(100 CHAR),
NAME	VARCHAR2(100 CHAR),
EMAIL	VARCHAR2(100 CHAR),
PHONE	VARCHAR2(100 CHAR),
NICK	VARCHAR2(100 CHAR),
REGISTER	VARCHAR2(100 CHAR)
);

CREATE TABLE MONEY(
MONEY_ID	NUMBER(10,0),
ITEM		VARCHAR2(150 CHAR),
PRICE		NUMBER(10,0),
DAY			VARCHAR2(20 CHAR),
ID			VARCHAR2(60 CHAR),
YEAR 		VARCHAR2(50),
MONTH 		VARCHAR2(50)	
);

CREATE TABLE TWITTER(
NAME	VARCHAR2(100 CHAR),
ADDR	VARCHAR2(100 CHAR)
);

CREATE TABLE DIARY
(
    DIARY_ID         NUMBER    NOT NULL, 
    DIARY_DATE       DATE      NULL, 
    CONTENT          CLOB      NULL, 
    DELETE_STATUS    CHAR      NULL, 
    CONSTRAINT DIARY_PK PRIMARY KEY (DIARY_ID)
);

--사진 DB

CREATE TABLE GIRLS
(
    G_ID    NUMBER           NOT NULL, 
    NAME    VARCHAR2(50)     NULL, 
    ADDR    VARCHAR2(255)    NULL, 
    TYPE    VARCHAR2(50)     NULL, 
    TAG1    VARCHAR2(50)     NULL,
    TAG2    VARCHAR2(50)     NULL,
    CONSTRAINT GIRLS_PK PRIMARY KEY (G_ID)
);

--위키 DB
CREATE TABLE WIKI
(
    WIKI_ID    NUMBER           NOT NULL, 
    WIKI_TITLE      VARCHAR2(255)    NULL, 
    WIKI_CONTENT    CLOB             NULL, 
    WIKI_CATE_ID    NUMBER           NULL
);

CREATE TABLE WIKI_CATE(
WIKI_CATE_ID  NUMBER        PRIMARY KEY,
WIKI_CATE_VAL VARCHAR2(255)
);


--만화
CREATE TABLE COMIC(
  COMIC_ID NUMBER,
  TITLE VARCHAR2(255),
  ADDR VARCHAR2(255),
  ADDR2 VARCHAR2(255)
);

--만화 본것 체크
CREATE TABLE COMIC_CHECK(
  CHECK_ID NUMBER,
  TITLE VARCHAR2(255),
  ADDR VARCHAR2(255),
  REGISTER_DATE DATE
);



